# taken from https://dev.to/abulka/comment/1dh3k thanks!
name: Release Citrus
on:
  push:
    tags:
      - "*"
jobs:
  release:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
    steps:

      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Install dependencies
        run: npm install
      - name: Get tailwind styles
        run: npm run tailwind:once
      - name: Publish to release using Electron Forge
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npm run publish
